create table users
(
    id           bigint generated by default as identity primary key,
    email        varchar(320) not null unique,
    password     varchar(255) not null,
    display_name varchar(100) not null,
    avatar_url   varchar(255),
    created_at   timestamp    not null,
    updated_at   timestamp    not null
);

create table chats
(
    id              bigint generated by default as identity primary key,
    type            varchar(20) not null,
    direct_key      varchar(50) unique,
    last_message_at timestamp,
    created_at      timestamp   not null,
    updated_at      timestamp   not null
);

create table messages
(
    id                bigint generated by default as identity primary key,
    chat_id           bigint    not null,
    sender_id         bigint    not null,
    client_message_id uuid      not null,
    content           text      not null,
    created_at        timestamp not null,

    constraint fk_messages_chat
        foreign key (chat_id) references chats (id),

    constraint fk_messages_sender
        foreign key (sender_id) references users (id),

    constraint uk_messages_sender_client_id
        unique (sender_id, client_message_id)
);

create index idx_messages_chat_created_id
    on messages (chat_id, created_at, id);

create table chat_members
(
    id                   bigint generated by default as identity primary key,
    chat_id              bigint    not null,
    user_id              bigint    not null,
    last_read_message_id bigint,
    joined_at            timestamp not null,

    constraint fk_chat_members_chat
        foreign key (chat_id) references chats (id),

    constraint fk_chat_members_user
        foreign key (user_id) references users (id),

    constraint fk_chat_members_last_read_message
        foreign key (last_read_message_id) references messages (id),

    constraint uk_chat_members_chat_user
        unique (chat_id, user_id)
);

create table user_blocks
(
    id              bigint generated by default as identity primary key,
    blocker_id      bigint    not null,
    blocked_user_id bigint    not null,
    created_at      timestamp not null,

    constraint fk_user_blocks_blocker
        foreign key (blocker_id) references users (id),

    constraint fk_user_blocks_blocked_user
        foreign key (blocked_user_id) references users (id),

    constraint uk_user_blocks_blocker_blocked
        unique (blocker_id, blocked_user_id),

    constraint chk_user_blocks_not_self
        check (blocker_id <> blocked_user_id)
);