create table refresh_tokens
(
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null,
    token_hash varchar(64) not null unique,
    expires_at timestamp   not null,
    revoked_at timestamp,
    created_at timestamp   not null,

    constraint fk_refresh_tokens_user
        foreign key (user_id) references users (id)
);

create index idx_refresh_tokens_user_id
    on refresh_tokens (user_id);