spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s

app:
  jwt:
    secret: ${JWT_SECRET}

  refresh-token:
    cookie:
      secure: false