spring:
  application:
    name: chat-app-server

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  devtools:
    restart:
      enabled: false

app:
  jwt:
    access-token-expiration: 3600