spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}